services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/credentials.json:/app/credentials.json
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    env_file:
      - ./ui/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
